### ISSUE TITLE
Discussion: How are you making git commits to the main branch? You're creating duplicate commits each time

### ISSUE THREAD

**Issue by DeflateAwning** [braillerap/BrailleRap#7]
How are you making git commits to the main branch? You're creating duplicate commits (same commit message, but twice) each time. You might have an easier time with git if you refine that process, and it'll make the change history in this repository cleaner too.

Happy to help advise!

**Comment by crocsg** [comment]
May i suggest you to analyze the complete commit log  and make some proposal.

**Comment by DeflateAwning** [comment]
Well, these are the two ways you're supposed to use git:

### Option 1: GitHub Desktop

1. Download github desktop
2. Clone the repository
3. Pull the latest version of the master branch, if you intend to commit directly to the master branch
4. Make some changes to the cloned files
5. Commit to the master branch
6. Push

### Option 2: Git CLI (Command Line Interface)

1. Clone the repo: `git clone <link to repo>`
2. Pull the latest version of the master branch: `git pull`
3. Make some changes to the files
4. Stage all changed files: `git add .`
5. Commit: `git commit -m "Description of changes goes here"`
6. Push: `git push`

Doing either of those options will avoid the very strange commit patterns you have going on currently
